### PR TITLE
Merged '23 UI of main menu button screens' branch to development

### LINKED ISSUE #23: UI of main menu button screens
### Develop the UI of each screen according to the wireframe:
- [x] UI of modes screen
- [x] UI of about screen
- [x] UI of settings screen**
- [x] UI of account screen**

** - no wireframe yet so base UI only

### PR DESCRIPTION
**Pull request by jiroblea**
### Created UIs of:
- Modes Screen
- About Screen
- Settings Screen
- Account Screen

please see the attached images:

image
image
image
image

### CODE REVIEW

**Comment by Serv08** [comment]
On the modescreen.kv, can the text holder for "Modes" use label instead of button?

**Comment by jiroblea** [comment]
> On the modescreen.kv, can the text holder for "Modes" use label instead of button?

Oh yeah, like the "About" in about screen, right? I will change it.

**Comment by jiroblea** [comment]
please see the attached image for recent changes:

image

**Comment by Serv08** [comment]
LGTM

**Review by Serv08 — APPROVED** [review]
LGTM

**Pull request merged**
